"""
Universal Multi-SDK Quantum Transpiler and Code Generator.
Exports visual circuits into runnable code across major quantum platforms:
1. IBM Qiskit 1.0+ (Superconducting)
2. Google Cirq (Google Quantum AI)
3. PennyLane (Xanadu Quantum Machine Learning)
4. Amazon Braket SDK (AWS Quantum)
5. OpenQASM 2.0 / OpenQASM 3.0 Standard
"""

from app.schemas import CircuitSchema

def circuit_to_qiskit(circuit: CircuitSchema) -> str:
    """Generates clean, runnable Python code using IBM Qiskit 1.0+ conventions."""
    lines = [
        "# ==========================================================",
        "# Generated by QuantumAI Learning Platform (SIH 2026)",
        "# Team Human X - Problem Statement 26140",
        "# ==========================================================",
        "from qiskit import QuantumCircuit",
        "from qiskit.quantum_info import Statevector",
        "import numpy as np",
        "",
        f"# Initialize {circuit.qubits}-qubit Quantum Circuit",
        f"qc = QuantumCircuit({circuit.qubits})",
        ""
    ]

    sorted_gates = sorted(circuit.gates, key=lambda g: (g.step, g.target))

    for gate in sorted_gates:
        name = gate.name.upper()
        tgt = gate.target
        ctrl = gate.control
        ctrl2 = gate.control2
        params = gate.params or {}

        if name == "H":
            lines.append(f"qc.h({tgt})")
        elif name == "X":
            lines.append(f"qc.x({tgt})")
        elif name == "Y":
            lines.append(f"qc.y({tgt})")
        elif name == "Z":
            lines.append(f"qc.z({tgt})")
        elif name == "S":
            lines.append(f"qc.s({tgt})")
        elif name in ("SDG", "S_DAG"):
            lines.append(f"qc.sdg({tgt})")
        elif name == "T":
            lines.append(f"qc.t({tgt})")
        elif name in ("TDG", "T_DAG"):
            lines.append(f"qc.tdg({tgt})")
        elif name == "RX":
            theta = params.get("theta", "np.pi")
            lines.append(f"qc.rx({theta}, {tgt})")
        elif name == "RY":
            theta = params.get("theta", "np.pi")
            lines.append(f"qc.ry({theta}, {tgt})")
        elif name == "RZ":
            theta = params.get("theta", "np.pi")
            lines.append(f"qc.rz({theta}, {tgt})")
        elif name in ("CNOT", "CX"):
            lines.append(f"qc.cx({ctrl}, {tgt})")
        elif name == "CZ":
            lines.append(f"qc.cz({ctrl}, {tgt})")
        elif name == "SWAP":
            lines.append(f"qc.swap({ctrl}, {tgt})")
        elif name in ("CCX", "TOFFOLI"):
            lines.append(f"qc.ccx({ctrl}, {ctrl2}, {tgt})")
        elif name in ("CPHASE", "CRZ"):
            phi = params.get("phi", "np.pi/2")
            lines.append(f"qc.cp({phi}, {ctrl}, {tgt})")
        elif name == "MEASURE":
            lines.append(f"qc.measure_all()  # Measure all qubits")

    lines.extend([
        "",
        "# Simulate Statevector",
        "state = Statevector.from_instruction(qc)",
        "print('Statevector:')",
        "print(state)",
        "",
        "# Print Probabilities",
        "probs = state.probabilities_dict()",
        "print('\\nProbabilities:')",
        "for bitstring, p in probs.items():",
        "    if p > 1e-4:",
        "        print(f'|{bitstring}⟩: {p:.4f}')",
        "",
        "# Draw ASCII Circuit diagram",
        "print('\\nCircuit Diagram:')",
        "print(qc.draw(output='text'))"
    ])

    return "\n".join(lines)


def circuit_to_cirq(circuit: CircuitSchema) -> str:
    """Generates runnable Google Cirq Python code."""
    lines = [
        "# ==========================================================",
        "# Google Cirq Export - Generated by QuantumAI Platform",
        "# ==========================================================",
        "import cirq",
        "import numpy as np",
        "",
        f"# Create {circuit.qubits} LineQubits",
        f"qubits = cirq.LineQubit.range({circuit.qubits})",
        "circuit = cirq.Circuit()",
        ""
    ]

    sorted_gates = sorted(circuit.gates, key=lambda g: (g.step, g.target))

    for gate in sorted_gates:
        name = gate.name.upper()
        tgt = gate.target
        ctrl = gate.control
        ctrl2 = gate.control2
        params = gate.params or {}

        if name == "H":
            lines.append(f"circuit.append(cirq.H(qubits[{tgt}]))")
        elif name == "X":
            lines.append(f"circuit.append(cirq.X(qubits[{tgt}]))")
        elif name == "Y":
            lines.append(f"circuit.append(cirq.Y(qubits[{tgt}]))")
        elif name == "Z":
            lines.append(f"circuit.append(cirq.Z(qubits[{tgt}]))")
        elif name == "S":
            lines.append(f"circuit.append(cirq.S(qubits[{tgt}]))")
        elif name in ("SDG", "S_DAG"):
            lines.append(f"circuit.append(cirq.S(qubits[{tgt}])**-1)")
        elif name == "T":
            lines.append(f"circuit.append(cirq.T(qubits[{tgt}]))")
        elif name in ("TDG", "T_DAG"):
            lines.append(f"circuit.append(cirq.T(qubits[{tgt}])**-1)")
        elif name == "RX":
            theta = params.get("theta", "np.pi")
            lines.append(f"circuit.append(cirq.rx({theta})(qubits[{tgt}]))")
        elif name == "RY":
            theta = params.get("theta", "np.pi")
            lines.append(f"circuit.append(cirq.ry({theta})(qubits[{tgt}]))")
        elif name == "RZ":
            theta = params.get("theta", "np.pi")
            lines.append(f"circuit.append(cirq.rz({theta})(qubits[{tgt}]))")
        elif name in ("CNOT", "CX"):
            lines.append(f"circuit.append(cirq.CNOT(qubits[{ctrl}], qubits[{tgt}]))")
        elif name == "CZ":
            lines.append(f"circuit.append(cirq.CZ(qubits[{ctrl}], qubits[{tgt}]))")
        elif name == "SWAP":
            lines.append(f"circuit.append(cirq.SWAP(qubits[{ctrl}], qubits[{tgt}]))")
        elif name in ("CCX", "TOFFOLI"):
            lines.append(f"circuit.append(cirq.TOFFOLI(qubits[{ctrl}], qubits[{ctrl2}], qubits[{tgt}]))")

    lines.extend([
        "",
        "# Simulate using Cirq Simulator",
        "simulator = cirq.Simulator()",
        "result = simulator.simulate(circuit)",
        "print('Final State Vector:')",
        "print(result.final_state_vector)",
        "print('\\nCirq Circuit:')",
        "print(circuit)"
    ])

    return "\n".join(lines)


def circuit_to_pennylane(circuit: CircuitSchema) -> str:
    """Generates PennyLane Quantum Machine Learning (QML) code."""
    lines = [
        "# ==========================================================",
        "# PennyLane (Xanadu QML) Export - Generated by QuantumAI",
        "# ==========================================================",
        "import pennylane as qml",
        "import numpy as np",
        "",
        f"# Define {circuit.qubits}-qubit default qubit device",
        f"dev = qml.device('default.qubit', wires={circuit.qubits})",
        "",
        "@qml.qnode(dev)",
        "def quantum_circuit():"
    ]

    sorted_gates = sorted(circuit.gates, key=lambda g: (g.step, g.target))

    for gate in sorted_gates:
        name = gate.name.upper()
        tgt = gate.target
        ctrl = gate.control
        ctrl2 = gate.control2
        params = gate.params or {}

        if name == "H":
            lines.append(f"    qml.Hadamard(wires={tgt})")
        elif name == "X":
            lines.append(f"    qml.PauliX(wires={tgt})")
        elif name == "Y":
            lines.append(f"    qml.PauliY(wires={tgt})")
        elif name == "Z":
            lines.append(f"    qml.PauliZ(wires={tgt})")
        elif name == "S":
            lines.append(f"    qml.S(wires={tgt})")
        elif name == "T":
            lines.append(f"    qml.T(wires={tgt})")
        elif name == "RX":
            theta = params.get("theta", "np.pi")
            lines.append(f"    qml.RX({theta}, wires={tgt})")
        elif name == "RY":
            theta = params.get("theta", "np.pi")
            lines.append(f"    qml.RY({theta}, wires={tgt})")
        elif name == "RZ":
            theta = params.get("theta", "np.pi")
            lines.append(f"    qml.RZ({theta}, wires={tgt})")
        elif name in ("CNOT", "CX"):
            lines.append(f"    qml.CNOT(wires=[{ctrl}, {tgt}])")
        elif name == "CZ":
            lines.append(f"    qml.CZ(wires=[{ctrl}, {tgt}])")
        elif name == "SWAP":
            lines.append(f"    qml.SWAP(wires=[{ctrl}, {tgt}])")
        elif name in ("CCX", "TOFFOLI"):
            lines.append(f"    qml.Toffoli(wires=[{ctrl}, {ctrl2}, {tgt}])")

    lines.extend([
        "    return qml.probs()",
        "",
        "# Execute and display measurement probabilities",
        "probabilities = quantum_circuit()",
        "print('PennyLane Measurement Probabilities:')",
        "for i, p in enumerate(probabilities):",
        f"    print(f'|{{i:0{circuit.qubits}b}}⟩: {{p:.4f}}')",
        "",
        "# Draw circuit",
        "print('\\nCircuit:')",
        "print(qml.draw(quantum_circuit)())"
    ])

    return "\n".join(lines)


def circuit_to_braket(circuit: CircuitSchema) -> str:
    """Generates Amazon Braket SDK Python code."""
    lines = [
        "# ==========================================================",
        "# Amazon Braket SDK Export - Generated by QuantumAI Platform",
        "# ==========================================================",
        "from braket.circuits import Circuit",
        "from braket.devices import LocalSimulator",
        "import numpy as np",
        "",
        "circuit = Circuit()",
        ""
    ]

    sorted_gates = sorted(circuit.gates, key=lambda g: (g.step, g.target))

    for gate in sorted_gates:
        name = gate.name.upper()
        tgt = gate.target
        ctrl = gate.control
        ctrl2 = gate.control2
        params = gate.params or {}

        if name == "H":
            lines.append(f"circuit.h({tgt})")
        elif name == "X":
            lines.append(f"circuit.x({tgt})")
        elif name == "Y":
            lines.append(f"circuit.y({tgt})")
        elif name == "Z":
            lines.append(f"circuit.z({tgt})")
        elif name == "S":
            lines.append(f"circuit.s({tgt})")
        elif name == "T":
            lines.append(f"circuit.t({tgt})")
        elif name == "RX":
            theta = params.get("theta", "np.pi")
            lines.append(f"circuit.rx({tgt}, {theta})")
        elif name == "RY":
            theta = params.get("theta", "np.pi")
            lines.append(f"circuit.ry({tgt}, {theta})")
        elif name == "RZ":
            theta = params.get("theta", "np.pi")
            lines.append(f"circuit.rz({tgt}, {theta})")
        elif name in ("CNOT", "CX"):
            lines.append(f"circuit.cnot({ctrl}, {tgt})")
        elif name == "CZ":
            lines.append(f"circuit.cz({ctrl}, {tgt})")
        elif name == "SWAP":
            lines.append(f"circuit.swap({ctrl}, {tgt})")
        elif name in ("CCX", "TOFFOLI"):
            lines.append(f"circuit.ccnot({ctrl}, {ctrl2}, {tgt})")

    lines.extend([
        "",
        "# Run on AWS Local Simulator",
        "device = LocalSimulator()",
        "result = device.run(circuit, shots=1000).result()",
        "print('Amazon Braket Measurement Counts:')",
        "print(result.measurement_counts)",
        "print('\\nCircuit Diagram:')",
        "print(circuit)"
    ])

    return "\n".join(lines)


def circuit_to_qasm(circuit: CircuitSchema) -> str:
    """Exports circuit into OpenQASM 2.0 / 3.0 compatible format."""
    lines = [
        'OPENQASM 2.0;',
        'include "qelib1.inc";',
        '',
        f'qreg q[{circuit.qubits}];',
        f'creg c[{circuit.qubits}];',
        ''
    ]

    sorted_gates = sorted(circuit.gates, key=lambda g: (g.step, g.target))

    for gate in sorted_gates:
        name = gate.name.upper()
        tgt = gate.target
        ctrl = gate.control
        ctrl2 = gate.control2
        params = gate.params or {}

        if name == "H":
            lines.append(f'h q[{tgt}];')
        elif name == "X":
            lines.append(f'x q[{tgt}];')
        elif name == "Y":
            lines.append(f'y q[{tgt}];')
        elif name == "Z":
            lines.append(f'z q[{tgt}];')
        elif name == "S":
            lines.append(f's q[{tgt}];')
        elif name in ("SDG", "S_DAG"):
            lines.append(f'sdg q[{tgt}];')
        elif name == "T":
            lines.append(f't q[{tgt}];')
        elif name in ("TDG", "T_DAG"):
            lines.append(f'tdg q[{tgt}];')
        elif name == "RX":
            theta = params.get("theta", 3.14159)
            lines.append(f'rx({theta}) q[{tgt}];')
        elif name == "RY":
            theta = params.get("theta", 3.14159)
            lines.append(f'ry({theta}) q[{tgt}];')
        elif name == "RZ":
            theta = params.get("theta", 3.14159)
            lines.append(f'rz({theta}) q[{tgt}];')
        elif name in ("CNOT", "CX"):
            lines.append(f'cx q[{ctrl}],q[{tgt}];')
        elif name == "CZ":
            lines.append(f'cz q[{ctrl}],q[{tgt}];')
        elif name == "SWAP":
            lines.append(f'swap q[{ctrl}],q[{tgt}];')
        elif name in ("CCX", "TOFFOLI"):
            lines.append(f'ccx q[{ctrl}],q[{ctrl2}],q[{tgt}];')
        elif name == "MEASURE":
            lines.append(f'measure q[{tgt}] -> c[{tgt}];')

    return "\n".join(lines)


def export_all_sdks(circuit: CircuitSchema) -> dict:
    """Returns a dictionary containing transpiled code across all supported quantum SDKs."""
    return {
        "qiskit": circuit_to_qiskit(circuit),
        "cirq": circuit_to_cirq(circuit),
        "pennylane": circuit_to_pennylane(circuit),
        "braket": circuit_to_braket(circuit),
        "qasm": circuit_to_qasm(circuit)
    }
